name = "RuleLynx"
uuid = "881ac0d9-e010-40e5-a4e8-9d7667d242e2"
authors = ["Doug Williams <m.douglas.williams@gmail.com>"]
version = "0.1.0"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
